# Generated by Django 4.0.5 on 2022-08-18 01:28

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=40)),
                ('ultimo_nome', models.CharField(max_length=40)),
                ('foto', models.ImageField(upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modalidade', models.CharField(verbose_name="modalidade",max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=40)),
                ('ultimo_nome', models.CharField(max_length=40)),
                ('curriculo_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano_documento', models.IntegerField()),
                ('resumo', models.TextField()),
                ('arquivo', models.FileField(upload_to='tccs')),
                ('palavras_chave', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.autor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.curso')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.orientador')),
            ],
        ),
    ]