# Generated by Django 4.0.6 on 2022-08-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=150, verbose_name='sobrenome')),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('modalidade', models.CharField(max_length=150, verbose_name='modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=150, verbose_name='sobrenome')),
                ('lattes', models.CharField(max_length=150, verbose_name='lattes')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('senha', models.CharField(max_length=150, verbose_name='senha')),
            ],
        ),
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('curso', models.CharField(max_length=150, verbose_name='Curso')),
                ('arquivo', models.CharField(max_length=150, verbose_name='Arquivo')),
                ('palavras_chave', models.TextField(verbose_name='Palavras chave')),
                ('autor', models.ManyToManyField(to='tcc.autor')),
                ('orientador', models.ManyToManyField(to='tcc.orientador')),
            ],
        ),
    ]
